### PR TITLE
Add DrumkV1 instruments list

### PR DESCRIPTION
**Pull request by JaviVilarroig**
Hi.

This PR just adds the list of instruments for DrumkV1.

Sorry for not having asked before, but was looking a very small change. :)

### CODE REVIEW

**Comment by JaviVilarroig** [comment]
Hi @original-male.
If you're not interested in this PR, just say it and I will close it.

**Comment by original-male** [comment]
Hi @JaviVilarroig, I'm not not interested. Just didn't see it. There was a harassment campaign going on that required me to disable github notifications, but now that GitHub has granted me a block on the chief harasser I was able to renable them.

Can you explain briefly how/why this drumkv1 map differs from the "standard" drum machine mapping of the Default instrument. (I say standard because of course there never was a standard for drum machines), but the map in Default covers most of them that I've encountered. Just want to be sure that this isn't redundant to an existing map.

**Comment by JaviVilarroig** [comment]
Hi @original-male .
Thanks for answering. And thanks for this great piece of software!! I'm just an amateur but your software has been realy making my life easier :)
I didn't mean anything negative. Is your project and you manage it. I know that sometimes you can become overwhelmed by managing all that in your free time so I was thinking that may be you were busy to answer. I'm sorry to listen that there was a harassment campaign against you, I hope things are better now.
About the map. It's the mapping for [DrumkV1](https://github.com/rncbc/drumkv1)  a lovely drumkit that I like to use with non sequencer. With that map any user of DrumkV1 will have the same instrument names in the drum machine and in non sequencer, making life a little bit simpler. 
I have been using it for myself for a couple of years already and I was thinking that by contributing it I can give back a little bit of what I have received from the free software community.
Thanks for your time and for this nice software.

**Comment by original-male** [comment]
Thanks for the kind words and for your patience.

I'm still a bit confused about this PR though. I installed drumkv1 to see what you were referring to. It looked to me like it was using the standard GM Drum mapping. So I checked out your branch and compared the Drumkv1.inst file to the GM-Drum.inst file, and they appear to be byte-for-byte identical?

Am I missing something or is the intention just that that "Drumkv1" should just be an alias for "GM-Drum"?

**Pull request closed without merging**
