### PR TITLE
Send a clients PID through /nsm/gui/client/pid after /nsm/gui/client/new

### PR DESCRIPTION
**Pull request by diovudau**
This adds a new message /nsm/gui/client/pid for a GUI everytime a client is launched, basically everytime /new is send. Arguments are the client id and the PID.

This enables a GUI to monitor and report CPU usage and RAM to the user, for example in a graphical way or as percentage.

### CODE REVIEW

**Comment by diovudau** [comment]
The second commit informs the GUI of the session root, after announce. 
Example usage:
This enables the GUI to show the user where the files actually are and offer a service to open the session dir in the default (xdg-open) file manager.

**Comment by diovudau** [comment]
Sorry, that should have been `/nsm/gui/session/session_root` and not `/nsm/gui/session_root`

**Comment by original-male** [comment]
What's up with the new session_root message?

**Comment by original-male** [comment]
Nevermind. I missed your previous comments.

**Comment by original-male** [comment]
Q: Why would the user care about CPU and RAM usage of only the process in the session? It's really only the total load that has any consequence, right?

Also, the GUI knowing the PID doesn't do any good (and is likely to be misleading/broken) in the case of a multi-machine session. Making that work multi-session would require doing the CPU and RAM (and whatever else) sniffing in NSMD itself, which would definitely be out of scope, IMHO, although I can see how it would be useful to know the load of each system in the session (esp. if one or more is headless).

**Comment by diovudau** [comment]
A: The user cares about individual resources to know if a program is using them beyond expectations. It is also a general indicator if a program is working or frozen etc.   
For multi-machine sessions: yes. This will return no information then. Still, to cover the majority of usecases (local session only) is worth having. 
I am *not* planning to implement this in your GUI and do a pull request, don't worry about bloat :) I am writing my own GUI at the moment.

How about the session root?

P.S. I just realized that github is automatically appending any commits to my own GH-"fork" automatically to this PR.  The one from a few minutes ago fixes my typo, but I will refrain from pushing more before this here is decided.

**Comment by original-male** [comment]
Sigh. Yes, by all means. Why contribute to the enhancement of an existing project when you can just create yet another skin for it that bypasses all of the hard work of actually thinking out and implementing the core functionality? How many GUIs does NSM need? Shall we integrate it into the Plasma Desktop next? FYI the nsm/gui part of the protocol is undocumented, internal, and subject to change. I personally wouldn't recommend putting all your eggs in that basket. The next asshole who decides to create another GUI may find a way to muck it up for you.

**Comment by diovudau** [comment]
Did you just call me an asshole?

This is from your own website:
> Don't like the NSM UI? You can build your own and communicate with the server via a simple OSC protocol.

I am contributing to this existing project by reporting bugs, suggesting improvements and sending code. For years. Most of them were never adressed or commented on, especially not the trivial ones I have added to your bugtracker years ago, which still surprises me. 

The alternative is to get impatient and create a fork and rename the project. And I don't want that because infrastructure needs to be centralised.

**Comment by original-male** [comment]
I notice that none of these people creating new GUIs bother to first discuss what's supposedly wrong with the provided GUI. I find your insinuation that you have absolutely no intention of helping to add this presumably wonderful new functionality to the existing GUI to be a very asshole-ish stance and insulting to NSM users who prefer a lightweight GUI. I honestly don't see how creating a fork is any worse than what's already been happening. You're of course free to do whatever you like, as am I.

**Comment by diovudau** [comment]
It is just a GUI that shows some more information 
I will not engage in unproductive online discussion with you in a github tracker, especially after an insult.

I have promoted and and supported your session management ideas and protocol for years, and will continue to do so.  But NSM is not a finished, perfect piece of software. Stability, fixing of erros and usability matter.

**Comment by falkTX** [comment]
There were a few tickets created along the years that were either rejected or simply ignored.
That counts as discussion in my view.

Sometimes, if you want to see something being done properly, you have to do it yourself.
You yourself created NON with very similar idea to this one.
I personally feel like NSM could be in a much better state than where it is now, and see people like @diovudau are going to be the ones actually making that happen.

**Comment by original-male** [comment]
"Properly" is certainly a matter of taste. It took me all of 30 second to poke several holes in this PR. Most new feature requests are simply not thought-out enough to be worth my or anyone's time. IMHO, the most powerful way to maintain software quality is to simply say "no" to poorly thought out ideas, scope creep, etc. You interpret that as a project being dead, etc. I see it as effort put towards quality assurance.

@diovudau is not proposing to improve NSM, and that is why this PR was closed (with prejudice!). This PR does not benefit NSM or its users. It would only benefit a different project with (probably) different goals. In this simple single-machine, launched from NSM case @diovudau that is targeting, he doesn't seem to realize the obvious fact that he could just look at the NSMD process group to get the information he needs and it doesn't require any addition to the /nsm/gui/ protocol to do so. Believe me, if someone came to me with a feature-complete PR that actually solved a problem, it would make my day. This kind of frivolous nonsense just pisses me off. Why do people refuse to stop and thing about what they want to do before they do it (and demand that others assist them in their foot-shooting activity?).

**Comment by grammoboy2** [comment]
Maybe good to note that this discussion wasn't here, when nobody cared
about NSM.

FWIW my pov. I find Jonathans arguments against new features very
convincing most of the times. It's clear that he really thought about
this. I think we all somewhat agree on this. I also think keeping it
simple stupid, makes NSM works as a session management implementation. I
doubt that implementation of all kinds of exotic features, will help NSM
at all. In a previous post I listed three small improvements which I
would like for the GUI NSM. As a user I don't really need more. NSM
support in applications is the big thing that helps NSM forward.

On the other hand, there is obviously a group of people who finds NSM
GUI lacking. Not really convincing to me, but ok. Some might find the
GUI toolkit looks boring too. At the end of the day, what's the problem
when those people build their own GUI with all these extra features?
This is a open question. One thing I can imagine, is that they will
never be satisfied and needs changes in the whole API next for all kinds
of stuff. The author of RaySession has already implemented a different
NSM file format for instance.

Does a alternative GUI helps or hurts the project. That's a interesting
question for me.

**Comment by diovudau** [comment]
So, what about the other commit. 
Reporting the session root to the GUI so it can show the complete paths?

**Comment by original-male** [comment]
@grammoboy2 It all depends on how good the alternative GUI is. Many people who like QT or GTK will prefer a GUI using that TK to the stock GUI even if the usability or performance suffers by it. (obviously there's nothing I can do about that, there's simply no way I could achieve the same performance with those TKs [not that this matters much in NSM's case]). I think the fact that developers of alternative GUIs shy away from implementing their own version of the daemon is indicative of a lack of sufficient care and commitment require to produce a superior GUI.

**Comment by original-male** [comment]
@diovudau I think that part it seems reasonable and useful, since I can't think of another way one could get that information. I'm not 100% pure I understand what you want to do with it though. One thing it seems it would be useful for to me is for the kind of git integration we've been discussing elsewhere.

**Comment by falkTX** [comment]
> I think the fact that developers of alternative GUIs shy away from implementing their own version of the daemon is indicative of a lack of sufficient care and commitment require to produce a superior GUI.

This is a loaded statement.

From what I understood, the point of alternative GUIs is to do just that, an alternative GUI.
It is meant to be compatible with the existing nsmd, there is no need to reinvent that.

**Comment by original-male** [comment]
@diovudau But isn't the information you want already in the "/nsm/gui/session/name" message?

**Comment by original-male** [comment]
@falkTX It's a loaded action. Creating a new GUI, is in essence, putting a new face (yours) on something someone else made. If it's a bad could GUI, it could give NSM bad name (a worse one, that is, since apparently everyone already hates the stock GUI). It also seems to me that the chief inconvenience of the Non project in general is a lack of a distro packages and/or difficulty installing. Re-implementing the daemon in one's favorite language and coding style would get around that.

**Comment by diovudau** [comment]
> @diovudau But isn't the information you want already in the "/nsm/gui/session/name" message?

/nsm/gui/session/name  sends two parameters, the simple name and the path relative to the session root.

**Comment by grammoboy2** [comment]
> I think the fact that developers of alternative GUIs shy away from
> implementing their own version of the daemon is indicative of a lack
> of sufficient care and commitment require to produce a superior GUI.
I think this is too pessimistic. Most of the people that makes a new
GUI, do it with good intentions, to make it better. Even if they make it
worse actually. Most of them realize that the API/daemon shouldn't be
changed, luckily enough.

**Comment by grammoboy2** [comment]
> I think this is too pessimistic. Most of the people that makes a new
> GUI, do it with good intentions, to make it better. Even if they make it
> worse actually. Most of them realize that the API/daemon shouldn't be
> changed, luckily enough.


Also it's hard to deny the fact that diovudau
<https://github.com/diovudau> actually cares a lot about NSM. Let's be
fair here.

**Comment by original-male** [comment]
@diovudau I see. I would accept the PR for the session_root message. Of course, it being part of a project with a different release cycle, your GUI should not rely on the message always being sent.

**Comment by original-male** [comment]
@grammoboy2 I'm sure everyone has good intentions in their own mind. Obviously my own interests are mostly limited to the betterment of *this* project. I also think fragmentation/duplication of effort is a very real and very depressing problem. I didn't embark on this project before engaging in copious discussion and analysis of the extant projects. I think anything that can be fixed should be fixed rather than re-implemented. Obviously I understand that this is, for various reasons, often impossible. The GUI/TK thing just seems so inconsequential to me. It's heartbreaking that we have to choose between having wide adoption and remaining bloat-free.

**Comment by grammoboy2** [comment]
@original-male Agree with you man. I don't understand the switch from 'we want to improve NSM', to, 'let's make another GUI'.  Uh.. we already have a GUI... two actually. You don't need the NSM GUI a lot actually when you're working with your music applications in a NSM session.

A new GUI doesn't improve my NSM experience significantly when I want to work with Muse, Radium, Seq64, Rakarrack, Guitarix etc. etc. 

On the other hand, i don't know if a alternative GUI is that bad for NSM, if it will make people happy.

**Comment by trebmuh** [comment]
Something which is very good with raysession is that it allows for translations.

**Comment by grammoboy2** [comment]
> Something which is very good with raysession is that it allows translations and that improves a lot for all the non-english readers.

I think this is a perfect example. You fix that 'problem' by writing a total new GUI?

**Comment by original-male** [comment]
@trebmuh Off topic. But yeah, theoretically that's possible to do with FLTK/NTK (a bit problematic because of the way the layout engine works, wildly different string lengths are hard to handle), but I've never personally figured all l18n stuff out. Patches welcome of course!

**Comment by original-male** [comment]
@original-male Honestly, given the strength of prejudice against non-big-2 toolkits, I was surprised that anybody outside of pure Non-* users was willing to tolerate the stock GUI at all.

**Comment by trebmuh** [comment]
@original-male it's not off-topic as far as I'm concerned. It's to demonstrate they RS has some advantages over NSM. Not to say that I'm very sad to read @grammoboy2 kicking down RS and/or its author all around the web while he doesn't understand all the roots.

I'm not a programmer so I'm not the one who will produce an i18n for NTK. What I can provide is a translation.

**Comment by grammoboy2** [comment]
On 06-03-2020 17:08, Olivier Humbert wrote:
> I'm very sad to read @grammoboy2 <https://github.com/grammoboy2> 
> kicking down RS and/or its author all around the web while he doesn't 
> understand all the roots.
My opinion is indeed that the RaySession author doesn't get it and that 
RaySession is not good for Linuxaudio at all. I'm not telling this all 
around the web, when the topic is at my table, I'll indeed give my clear 
opinion. Don't want to find myself in a Linuxaudio Session Management 
mess again. Feel free to have a different opinion though, all though I 
don't think this is the right place to discuss the opinion of grammoboy2.

**Comment by trebmuh** [comment]
Just : lol.

**Comment by sub26nico** [comment]
From a (just) user experience, RS is easier to deal with. I tried NSM (and really love NON stuff) but RS gives me better times. A  part of it is the nice talk to the dev who never bash anybody and listen (and answer) user's questions. Far, far away from 'doesn't get it ' and 'not good for Linuxaudio'.
My 2 cents.

**Comment by grammoboy2** [comment]
I agree communication could be nicer and improved. 

That's said, at the end I prefer software  from a developer who has proven that he 'gets it', when it comes to session management, compared to a implementation by 'mister nice guy' and less skilled programmer who seems to lack vision, knowledge of SM history and who seems re-introduce a session mess again.

**Comment by trebmuh** [comment]
Just : lol (2nd edition).

Can you see how bad is your communication here? And you're wanting to improve the (nichy) linuxaudio realm? And you claim that other people are miscommunicating?

**Comment by grammoboy2** [comment]
Which part was too blunt? Less skilled programmer, lack of  history knowledge or re-introducing a session mess again? I didn't  Sorry mate, that was the message, better to tell the truth then being too friendly and find yourself in a mess again.

**Comment by original-male** [comment]
Anyone know how to ban users on github?

**Pull request closed without merging**
