### PR TITLE
LV2 support

### PR DESCRIPTION
**Pull request by falkTX**
This pull request brings (initial) LV2 support for Non-Mixer.

Some basic features are supported (bufsize and options). This if of course FX only.
Having custom UIs is not something that can be easily done with NTK, and I'm not much interested on it right now.
We can go on a per-plugin basis, getting the needed features working as needed.

The plugin chooser dialog needs some updating, it currenly only lists LADSPA in the combo-box, I'll leave that to you.
The code style doesn't always matches yours, sorry. If this is a big issue I can update it.

### CODE REVIEW

**Comment by rhetr** [comment]
LADSPA plugins aren't showing up in the plugin chooser

**Comment by georgkrause** [comment]
@original-male i want this!

**Comment by geraldmwangi** [comment]
This would be cool

**Comment by falkTX** [comment]
I've updated the PR against latest git sources, merged the different commits into a single one.
Should make it easy to patch the code.

On github, just browse the commit and add '.patch' at the end of the url, like this:
https://github.com/falkTX/non/commit/87437d04710a7cf92eca310d79b55f624f178727.patch

**Comment by simonvanderveldt** [comment]
@original-male any chance this will ever get merged?

**Comment by original-male** [comment]
@simonvanderveldt I'm not sure... 

The reason I didn't implement LV2 support myself wasn't because I couldn't. The existence of this patch doesn't change anything about LV2 that made it unappealing, and AFAIK, LV2 itself hasn't changed much since I made that call.

Every time I look at LV2, I am repulsed. LADSPA is KISS, one header file dependency and relatively straight-forward. LV2 is like the opposite of KISS. It's like FART: Forget About Representing Terseness. It reminds me of something from IBM. The dependency is like 6 different little libraries that no one will ever use for anything else. And all that this complexity really buys you is shitty in-process GUIs that crash your host program.

As far as integrating it into Non goes... I think the answer is no. Maybe some kind of LV2->Ladspa wrapper plugin would be acceptable. 

I'm simply not going to install the LV2 libs on my machine. I don't use it, I don't have a use for it, it has never worked when I tried to use it, and that makes it hard to develop and test an application that depends on it. You'd have to pay me to work with an IBM software product, and you'd have to pay me to work with LV2. There's just no joy in it.

**Comment by fundamental** [comment]
@original-male as a clarification, are you opposed to non having LV2 support or are you opposed to you having to deal with the additional maintenance burden that LV2 support would entail?

I know when I've dealt with LV2 it's certainly seemed very much like a big enterprise design with its complexity, so I understand where you're coming from. That said, it does seem to be the general direction that linux audio plugins have decided upon, so there are advantages to having some support for the standard.

**Comment by original-male** [comment]
@fundamental That's only part of it. It's a cost:benefit analysis. Every time the LV2 issue has been brought up in the past, I asked the question "What specific LV2 plugin do you need?" and the answer, if I could get it, was always something that was really just a port of an LADSPA plugin. So LV2 costs: developer time, lines of code (which is redundant to the LADSPA support), debugging, dependencies (and the associated bug reports when they can't be found). But what is the benefit? Access to plugins that LADSPA already provides access to in a simpler, more stable, more mature way? Or access to LV2 only plugins which are things like synths which aren't really relevant to a an audio mixer and should arguably be stand alone JACK clients (and may already exist as stand-alone clients or can already be hosted in jalv et al)? With LV2, all I see is cost. I don't see that it buys me anything, other than do say Non has LV2 support, which isn't worth anything to me, because I dislike everything about LV2's design and implementation and don't want to be associated with it if I can help it. (It would be nice to not be associated with X11 either, but I can't help that [yet].)

And that gets us to your final point: LV2 being the 'direction the community has decided upon'. This is the thing about LV2 that really irks me. It is not LADSPA V2, as the name implies. It's trying to trick people into thinking it's a continuation, an upgrade, enhancement or whatever, when really it's something almost entirely different with a different philosophy, and different (and very esoteric [ask drobilla about nesting plugins within plugins some time, just make sure you have some aspirin handy...]) goals etc.
 
If LADSPA is lacking, by all means let us improve it. Or if there's something people really need that's only available as an LV2 plugin, why not just port it to LADSPA? LADSPA is perfectly adequate for anything relevant to a mixer.

Perhaps I should point out that I don't even like the concept of in-process plugins period and only support LADSPA begrudgingly because it's simple and most of the plugins have been around long enough to be stable.

**Comment by fundamental** [comment]
Thanks for the clarification.

Per LV2 specifics that are useful to a mixer, the inline display extension comes to mind. Ardour has used this to display plugin data (VU/EQ settings) inline with a mixer (e.g. http://robin.linuxaudio.org/tmp/inline_display.png ). For mixing I could see that being quite useful, but it sounds like something that would be philosophically out-of-scope with what you're trying to build.

Anyhow, I think it's important to know both what a project is trying to be and what it is not trying to be. It seems like LV2 is right on the border of what's in-scope and what's out-of-scope for the mixer.

**Comment by original-male** [comment]
@fundamental Yes, the inline display thing is a perfect example of what I'm talking about. It's something that people think is cool, but nobody seems to have stopped to ask, "is it a good idea?" Is drobilla's world where everything is a plugin really a world we want to live in? How is the host supposed to ensure that the plugin's scope GUI meets its standards of performance? That it reflects the design of the rest of the host application and integrates well and fully with the application's UX? Why can't a host provide its own scopes, why does a plugin need to do that? I feel like LADSPA intentionally and rightfully avoids opening this Pandora's box. It works for Ardour because Ardour and LV2 are highly integrated (developers communicate amicably, use the same GUI toolkit etc.). This creates an illusion that hosts and plugins can get along in a way that isn't necessarily true in the wider world outside of Ardour, where everything is heterogeneous.

W/r/t scope, LV2 is not intended to be a replacement for LADSPA, it's intended to be a replacement for JACK (both PBD and drobilla seem to be on the same track here, pull everything into Ardour as an LV2 plugin and use platform audio directly in a monolithic application, without JACK), and that's not a direction I'm comfortable in going, for reasons which should be obvious---especially not with the way it's implemented and not without some operating system level support for isolating in-process plugins.

**Comment by fundamental** [comment]
+1 to the commentary on the Ardour + LV2 dynamic. LV2 is driven by relatively few individuals and it has limited adoptions. This certainly has lead the standard into many esoteric directions.

> where everything is a plugin really a world we want to live in?

Personally, no. There seems to be plenty of user demand for it though as many people prefer the workflow keeping everything in one application. There are advantages to the organization presented by some hosts, easier automations with plugins, fewer context swaps for complex setups, and a more consistent feel to interactions. I'm much more on the independent non-trivial applications + very simple plugins (with out-of-process UI) side of things. That said, I try to support LV2/other-plugin-options in the name of making things work in the way that users currently appear to demand.

> How is the host supposed to ensure that the plugin's scope GUI meets its standards of performance?
> That it reflects the design of the rest of the host application and integrates well and fully with the application's UX?

Without creating a list of 'good' vs 'bad' plugins it's basically impossible. That is part of the irksome part of plugins; the quality of user experience depends upon something that's outside of your control. I know with Zyn and various plugin versions it's difficult to see how user experience is shaped by host specific issues (typically VST rather than LV2, but same general idea).

> it's intended to be a replacement for JACK

Yeah, I wish that wasn't the direction that the plugin standard has been taken. JACK + NSM + some more metadata + floating point automations would be a very nice alternative. At that point all that plugins would gain (IMO) would be fewer context swaps (and I think they're worth the extra system stability). If I can ever get Zyn to a good point for being feature complete (from my perspective) I think I'd like to help enhance and polish user facing portions of NSM to see about reminding people about the fact that not everything needs to be a plugin per say.

**Comment by ssj71** [comment]
I've been thinking about this for a little while. Perhaps the answer would be to remove all plugin support from mixer and instead use something like carla-single with some deeper NSM integration that exposes the parameter data for easy automation in timeline. I think some workflow like jalv.select would basically turn any plugin into a standalone app without any additional hassle to the user.
That of course is a fair bit of work, but would that be a good direction that would fit best with non's goals? If carla was leveraged, falktx is fairly motivated to support all kinds of plugins, all that would need to be collaborated/added would be deeper NSM support, and that may already be there.

**Comment by original-male** [comment]
@ssj71 Part of the problem here is that there's a whole morass around even the idea of what a plugin is. In LADSPA, a plugin is a very simple (usually stupidly simple, as in you could just copy and paste 10 lines of code into the host and have the same functionality built in) bit of DSP code with some well-defined parameters. So far so good. Yes, a plugin can corrupt the memory of the host, which sucks, but like I said the code is so simple that it's easy to audit.

LV2 opens a whole metaphysical can of worms by extending what a plugin can be to literally anything. A plugin can be an application which hosts its own plugins, which hosts its own plugins (including itself! eek!) etc. This is the kind of thing that has literally driven philosophers and mathematicians insane (and is something one would be wise to avoid entirely if one values one's cerebral integrity.)

In the case of a mixer, and simple-type plugins, a mixer strip/chain is the most efficient unit to house them--having a separate JACK client for each tiny little bit of DSP code that a plugin encapsulates would indeed become a performance problem (not a huge one, but it would start to limit the number of strips a machine could handle).

In the case of LV2's ∞ly nesting-type plugins, it's a different story, and these things should be in their own JACK clients, enclosed in as much ∞-proof tinfoil as you can promote. However, one of the things missing from LV2's everything-and-the-kitchen-sink-plus-and-∞-of-same architecture is a way to differentiate between simple-type DSP plugins and ∞-type nutcrunching-cluster-fscks. Which is a profound oversight, IMHI, and not the only one in LV2.

**Comment by original-male** [comment]
@ss71 Also... you reminded me. I did once upon a time play with the idea of having each strip in non-mixer run in a separate process (in addition to a separate JACK client). It obviously requires separating the backend from the GUI (once upon a time non-timeline had a separate GUI and an engine process too). This makes the application far more complex though, not to mention much, much slower (esp. timeline), so I scrapped the idea. I still like the idea conceptually though. Basically the way I have a single process with multiple clients in NM is an off-label use of JACK.

**Comment by ssj71** [comment]
@original-male Interesting. Thanks for the insights. I'll keep thinking about what "the best" approach may be.

**Comment by original-male** [comment]
@ssj71 That's certainly a tough one. All I know is that a recursive interface whose end is to recreate the  functionality of the OS in a less-robust way (as a single OS-level process) and whose model allows 'processes' to contain other nested OS/'processes' can't possibly be the best approach. Might as well toss some VMs in there, maybe some a bytecode format and JIT compiler. It's a long way from that 10 lines of DSP code we started with.

A while ago I was working a new plugin API, to address some of the issues with LADSPA/DSSI without opening insane new dimensions of recusion in the process, but it kind of fizzled out. It would be hard to gain traction with yet another format anyway and I think I missed the boat on that one.

**Comment by jrigg** [comment]
> And that gets us to your final point: LV2 being the 'direction the community has decided upon'. This is the thing about LV2 that really irks me.

You aren't the only one. I've been gradually removing LV2 plugins from my DAWs and am currently down to about six. I got tired of large numbers of LV2 plugins breaking every few months when the LV2 spec or some library it depends on changed. The assumption that everyone wants a fancy GUI in order to do very basic things is also irritating. On my next upgrade I'll probably ditch LV2 entirely.

Non-Mixer is almost perfect the way it is IMO, and the KISS philosophy of Non was a major factor in my decision to switch to it from Ardour (after 8+ years) about three years ago.

**Comment by jrigg** [comment]
> **@ssj71:** Perhaps the answer would be to remove all plugin support from mixer

A mixer without any plugin support at all would be fairly useless. For those of us who prefer to keep their DAW systems as simple as possible, heavyweight external hosts like Carla are not an option.

**Comment by unfa** [comment]
Oh, so that's why there's no LV2 support in Non-Mixer!

I'm don't agree that LADSPA is all an artist would ever need. There's many things I need that are not possible with LADSPA, or are a royal pain.

In-line displays? If used properly can give mixer strips a ton of readability, and I like them a lot, often reducing the amount of actions I need to perform to obtain certain information.

Not to mention that LV2 plugins can be both audio and MIDI processors, and instruments. Also stuff like x42-autotune is possible - an audio processor with an aux MIDI input giving unique possibilities. Sure LV2 isn't as minimal as LADSPA, but as an artist - I can live without LADSPA and DSSI, but I can't live without LV2.

For music productions and sound design LADSPA feels like a rusty old bucket leaking water. It was a start and we're past that era (hopefully?).

I don't mind legacy LADSPA support, but when I see software not supporting LV2 (like LMMS) I frown and shake my head in disappointment.

**Comment by grammoboy2** [comment]
On 7/1/20 12:28 AM, unfa wrote:
>
> Oh, so that's why there's no LV2 support in Non-Mixer!
>
> I'm don't agree that LADSPA is all an artist would ever need. There's 
> many things I need that are not possible with LADSPA, or are a royal pain.
>
> In-line displays? If used properly can give mixer strips a ton of 
> readability, and I like them a lot, often reducing the amount of 
> actions I need to perform to obtain certain information.
>
> Not to mention that LV2 plugins can be both audio and MIDI processors, 
> and instruments. Also stuff like x42-autotune is possible - an audio 
> processor with an aux MIDI input giving unique possibilities. Sure LV2 
> isn't as minimal as LADSPA, but as an artist - I can live without 
> LADSPA and DSSI, but I can't live without LV2.
>
> For music productions and sound design LADSPA feels like a rusty old 
> bucket leaking water. It was a start and we're past that era (hopefully?).
>
> I don't mind legacy LADSPA support, but when I see software not 
> supporting LV2 (like LMMS) I frown and shake my head in disappointment.
>

https://github.com/falkTX/non

https://github.com/falkTX/non/commit/87437d04710a7cf92eca310d79b55f624f178727

Packages in kxstudio do have lv2 support afaik.

**Comment by unfa** [comment]
Ah, thanks! I'm currentyl on Manajro, maybe there's an AUR PKGBUILD for that...

**Comment by grammoboy2** [comment]
On 7/1/20 10:47 AM, unfa wrote:
>
> Ah, thanks! I'm currentyl on Manajro, maybe there's an AUR PKGBUILD 
> for that...
>
It wouldn't surprise me that Arch Linux has that version too, but not sure.

You've to thank Falktx for the LV2 patch.

**Comment by Teteros** [comment]
> I've completely removed LV2 from my DAWs. I got tired of large numbers of LV2 plugins breaking every few months when the LV2 spec or some library it depends on changed.

I think the situation changed a bit regarding that since 2017, many plugins are using native opengl/x11 calls and using native toolkits in LV2 plugins like qt/gtk is pretty much deprecated. The instability in some DAWs was mostly due to this I think.

It's how the GUIs were implemented, not the fact they are there.

**Comment by jrigg** [comment]
> many plugins are now using native opengl/x11 calls and using native toolkits in LV2 plugins like qt/gtk is pretty much deprecated

This is certainly an improvement, but IIRC the problem I had at the time was due to a change in the LV2 spec which made it more strict about the syntax of plugin .ttl files. A lot of existing plugins wouldn't load in jalv after the change.

I've relented slightly since that  2017 post and have installed a small number of LV2 plugins that don't have LADSPA or standalone equivalents, eg. noise-repellent. I remain wary of future breaking changes in LV2 however, and have no plans to install more unless it's absolutely necessary.

**Comment by falkTX** [comment]
To be fair, we were lacking in the tools to analyze and validate lv2 plugins back then.
Since quite a few developers rushed to make plugins, a few of them ended up broken.

Nowdays we have great collections such as:
https://lsp-plug.in/
https://x42-plugins.com/x42/
https://github.com/iurie-sw/geonkick
https://github.com/pdesaulniers/wolf-shaper
https://github.com/sadko4u/tamgamp.lv2
http://www.zamaudio.com/?p=976
(and many more. could mention Calf but not everyone likes their DSP plus being tied to Gtk makes them unreliable at times)

We now even have full zynaddsubfx as a plugin!

3 years ago or more, a lot of these plugins simply did not exist.


In the beginning we had quick ports of LADSPA plugins, and also quick hacks.
The hacky plugins that were rushed to release are now either fixed or completely unmaintained (so not to be used).

As a plugin host developer, most of the crashes and misbehaving stuff I have seen from plugins are either:
1. obviously unfinished plugins that are not to be trusted for serious work/compositions (luckily the amount of great plugins we can use today is much higher than the bad ones)
2. commercial plugins that did not bother to check linux support much or at all (u-he are notorious for the most random crashes, also JUCE stuff)

**Comment by grammoboy2** [comment]
Not sure if people where enthusiastic about these results if you told them at the beginning of LV2 that this would be the result within 10 years (?) of development...

Looking from it at a outsider, it looks to me like many developers say they are 'overwhelmed' by LV2. I think the idea of LV2 is from a time where we thought the Linux Desktop will be far more popular then it is now. LV2 as direct alternative for VST, a plugin standard which can do all the things commercial parties find interesting and even more.

Given the fact that LV2 has landed now (but no major company implemented it afaik, not even when they released software for linux) a more simple plugin API might be much better for the linuxaudio as a volunteers community, today then LV2 is. A simple plugin API that is good for the community, not a plugin API that needs to compete with the commercial world.  So I think 'male' wasn't very far off 'back in the days' with his view on LV2.

**Comment by falkTX** [comment]
That is such a naive simple-minded thinking.
Companies not implementing LV2 is a complex problem, not a simple one to attribute like that.
Case in point: even when having the code ready-to-go for more than 6 years, JUCE still does not support LV2 officially. I wrote the wrapper code many years ago, but they never accepted it. It has nothing to do with the effort of implementing it, since even that out of the picture, they still do not support it. In the end, it is all about a business decision of having to maintain and support a new spec.

The same situation is not unique to LV2. Even one of the biggest audio companies that exist today, Steinberg, is having major problems making developers use their "new" VST3 spec. Situation got so bad that they decided to make it illegal to register new VST2 plugins and even issuing copyright strikes (DMCA) to projects that were still doing so.
The biggest reason devs are moving to VST3 right now is because they are being forced to.
VST3 is as old or even older than LV2, going back to at least 2006.
Oh and VST3 on Linux is still a joke, only have received Linux support earlier this year. Even though I dislike VST3 a lot, it would be unfair to say VST3 on Linux only happened now because it is not good. In reality, it has everything to do with business decisions from a very big company.

**Comment by falkTX** [comment]
Oh regarding companies doing LV2... at least the ones who care.
https://www.modartt.com/ is a great example, they support LV2 since a few years now (I helped them make that happen). They use JUCE, but unlike JUCE devs, they care enough about Linux users to give support for LV2.

https://github.com/kushview/Element/ is a JUCE-based host that implements LV2 but I would dare predict that even with that code 100% working, it won't be made/integrated info official JUCE either.

I have been seeing a few companies recently releasing lv2 plugins, mostly out of frustration with vst3.
But I don't use them myself, so I do not recall their names. But I know at least 2 plugin frameworks added lv2 now, with the lv2 version even working before the vst3 one (vst3 is very odd when it comes to the UI idle loop, makes it very hard to implement)

**Comment by grammoboy2** [comment]
As I said, I'm no developer, just a thing I see from the outside, in that sense it's certainly simple and naive. I do agree that acceptance by companies is a different and a very complex problem. 

But the fact that you need to help all those projects to make 'it happen', raises the question, why they would they need your help. With a simple plugin api as male seems to have suggested in this thread, they wouldn't need your help.

I don't think Pianoteq is a good example actually. It's just a rare case where the main develop has a linux background and supports it, and it still needed your help apparently.

I saw the video of the 'tracker' implementation in Ardour at Sonoj, where the developer also said, that he found LV2 too overwhelming, and you (as LV2 booster?) offering him to port his synth to LV2. But that doesn't solve the problem. In the ideal world that develop shouldn't have to be overwhelmed by a plugin API probably.

(In general I think we (including myself) tried too hard to make Linuxaudio interesting for the mainstream Windows/OSX user, linuxaudio is probably better served with a more linux specific approach.)

**Comment by falkTX** [comment]
> As I said, I'm no developer



> But the fact that you need to help all those projects to make 'it happen', raises the question, why they would need your help

Only raises the question because you have no idea what you are talking about ;)

The offer to help is quite a normal thing to do to welcome completely newcomers to a new API, specially back then when LV2 was still unpopular.

It is not that LV2 is overly complicated, it is not much so than AU or VST3, but it is a big shift in design compared to what some developers are used to.
LV2 has, for very good reasons, separation of UI and DSP, separation of binary and meta-data and full-range parameters (instead of normalized like many including VST do).
VST2 had the idea of separate meta-data via VSTXML, but I have not found 1 single plugin that uses it. VST3 has some weird UI -> controller -> DSP paradigm that developers can use, but feels very confusing. I would certainly need some easy introduction on that topic before I can even understand what they are trying to do.

The fact is, LV2 is still very unpopular.
It is popular on Linux, but most people do not use Linux, so it does not help much.
(where our community matters, LV2 is the go-to spec these days without question)
By the simple fact of an API being less popular, it leaves the impression of being harder to use.
The same thing is said over and over about how Windows is so much better and simple than any Linux distribution, but from an objective point-of-view, that is simply not the case anymore for many people, it is simply that most are used to how Windows looks and works.

Why don't you look at words from an actual developer that researched LV2 more deeply than just surface level?
http://lists.lv2plug.in/pipermail/devel-lv2plug.in/2019-March/001911.html

**Comment by grammoboy2** [comment]
Being not a developer doesn't mean I've no idea where I'm talking about, that's quite the other side of the line. Lot's of people making all kind of important 'meta' choices, without knowing the exact details. Sometimes it even helps when people are looking at it from a distance. 

I see people saying they are overwhelmed by LV2, that LV2 is opposite of KISS or that they don't use it (Fons Adriaensen). From other projects I know, more sophisticated or technically better, is quite subjective and doesn't have to tell a lot about whether it is the best solution for a 'problem'. Pretty often, it is the other way around, that a simple solution works better.

**Comment by unfa** [comment]
I think that demanding we downgrade Linux audio to a simpler plugin API (LADSPA?) and hence drop the features LV2 provides doesn't sound like a good idea to me.

There's now a great repository of fantastic LV2 plugins that provide great user experience and make the Linux audio a viable platform for modern music and sound production. If you told me tomorrow I can't have LV2 any more - I would be forced to use LinuxVST, and I prefer not to, unless I have no other choice (like with AirWindows plug-ins).

I don't think that the drive for custom GUIs, complex port configurations and control handling among other features of LV2 is caused by "trying to get competitive". I think these things exist, because people who love Linux audio and free software enacted to have decent tools, and not be using LADSPA forever.

For sure LV2 isn't going to be as simple to make plugins with, but there's frameworks like DPF that help with that, and a lot of people who can help newcomers. And no matter this simple the API would be - new developers would still need someone to help them figure it out.

On the other hand one could say that maybe a higher effort required to make a working LV2 plug-in helps weed out plugins that are made and published by people who have no idea what they are doing.

Programmers can start learning by creating LADSPA plugins which are still wifely supporter, and later jump into LV2 for "the real deal". It's like prototyping your tool in Bash and later going for Python (I'm not really a programmer myself, so excuse if I'm botching this analogy).


And for non-programmers, there's even Mephisto.lv2 which is a set of LV2 plugins that can be programmed live using FAUST. So even lower skill threshold to get some sound processing prototyped.

**Comment by grammoboy2** [comment]
I'm not suggesting to remove LV2. I'm sure it will be useful for a lot of projects and it wouldn't make much sense to ditch it. I'm also totally NOT the person to say anything about that, just for clarity. :) 

I just wonder if a more simple plugin API next to LV2 would help the community. Not LADSPA, but, let's say a LADSPA version 2.0 (yes, I know LV2...), which is KISS, simple and clean. Where people like male and fons (just as example(!)) would agree on. A KISS plugin format which is more suitable for a 'volunteer/free-time/hobby-developer type of environment, where you need simple stuff do get things done that works reliable and keeps working reliable without wasting too much time on things.

So you're not downgrading anything, just add a option that could be more suitable for a niche community as linuxaudio is.

Of course, disadvantage would be having to support another plugin format in hosts, but if it's really simple and clean, that _might_  not be a huge problem.

Anyway, I shared my thought and made my point I hope. It's not up to me if it's a good or bad idea at the end. ;)

**Comment by jrigg** [comment]
Is this argument even worth having? Some (like me) appreciate minimalism in software, others like a full set of features and pretty GUIs. Neither is wrong.

It's unreasonable to expect a developer with a strong preference for either way of working to change their fundamental design philosophy.  Don't like it? Create something you do like or use something else.

**Comment by unfa** [comment]
Yeah, I think we're getting nowhere. Everyone will do their own thing in the end.

I guess that if a significant part of libre audio community needs something simpler than LV2 but more powerful/modern than LADSPA/DSSI - it's gonna emerge. Just like LADSPA, DSSI, and LV2 emerged before. But I think it'd be wasted effort that could be better spend perfecting what we have and building on top of it - maybe perfecting frameworks for LV2 plug-ins to make it easier to work with them?

A new plug-in format spec. could be the best design in the world, but it's going to be useless unless it sees wide adoption. And with limited resources the libre software community has - it better be worth the effort.

Also if we ever want to see libre audio plug-in formats being adopted in proprietary software - we better have a single horse to bet on, or the drive will dissipate and fizzle out.

I think there's little change LV2 will get widely adopted outside of libre audio and Linux - add another competing format and we're shooting our own foot again.

**Comment by falkTX** [comment]
> I see people saying they are overwhelmed by LV2, that LV2 is opposite of KISS or that they don't use it (Fons Adriaensen).

From my talks with Fons, he seems pretty unaware of what LV2 could do or how it works.
It is just not needed for him, so all he does are JACK standalones.
When I showed him a few things LV2 allowed and a very basic scenario where they are used, he was quite positive about it.
Robin has been porting a lot of Fons DSP to LV2 plugins, with his permissions (only asking that project is renamed)
So Fons simply does not do LV2 because he does not personally needs to.

btw, here are the ported plugins
https://x42-plugins.com/x42/x42-eq
https://x42-plugins.com/x42/x42-limiter
https://x42-plugins.com/x42/x42-compressor
https://x42-plugins.com/x42/x42-autotune

It has been quite the long time since I saw any kind of LADSPA related news.
The last one was about ladspa.org domain going out of date, and someone had to step up to buy and maintain it because no developers care anymore.
The community has moved on and chose LV2.
It is not about the pretty GUIs, it has become annoying that you still say this after repeatedly being told it is not the case.
All the extra properties on top of GUI-less plugins like:
http://lv2plug.in/ns/ext/port-groups
http://lv2plug.in/ns/ext/port-props
http://lv2plug.in/ns/extensions/units

are **extremely** useful for hosts to create a nice and user friendly + understandable generic UI.

with patch and state extension, we can even have gui-less plugins that request files from the host, like IR wav file for convolution, or SFZ for sampling, hydrogen drumkit, scala tuning files... lots of stuff that simply was not possible by design on LADSPA.
It is fine if you want to have simple FX-only plugins, but at this point most of the world does not.

We do NOT want yet another plugin format. The upcoming VST3 vs LV2 that I see happening on Linux soon is already going to be enough of a problem... It would a massive pain for the community to have to deal with yet another spec, that is mostly just going to end up ignored anyway. We do not want another session-manager mess type of situation here.
NSM was picked as the SM API to use, the same way as LV2 is the plugin format to use as well. Some developers from commercial background will port their plugins in VST3 format only, but this is because it is way less effort to port their existing code for the small adjustments Linux needs vs supporting a whole new spec they know nothing about.



> Anyway, I shared my thought and made my point I hope. I can imagine having another plugin format isn't the best idea... but hey... It's not up to me if it's a good or bad idea at the end. ;)

It is up to me and the other developers to judge, and from my side it is a terrible idea.
And no, you did not made your point. Your assertion on Fons' ideas is untrue, and you have no expertise to tell if a plugin API is going to be simple or not. LV2 surely has its issues, but it is by far the best we have right now. The only comparible (in terms of quality) API would be AudioUnits, but that is only for macOS.

Please, please, stop talking out of your ass.

**Comment by grammoboy2** [comment]
> It is not about the pretty GUIs, it has become annoying that you still say this after repeatedly being told it is not the case.

Huh?! You must have read a other discussion then. 
Sorry mate, I must have stepped on your dick somewhere. Let's stop this discussion.

**Comment by falkTX** [comment]
> > It is not about the pretty GUIs, it has become annoying that you still say this after repeatedly being told it is not the case.
> 
> Huh?! You must have read a other discussion then.

You forgot to edit a previous comment, so this is still relevant ;)

> Every time I look at LV2, I am repulsed. LADSPA is KISS, one header file dependency and relatively straight-forward. LV2 is like the opposite of KISS. It's like FART: Forget About Representing Terseness. It reminds me of something from IBM. The dependency is like 6 different little libraries that no one will ever use for anything else. And all that this complexity really buys you is shitty in-process GUIs that crash your host program.




> Sorry mate, I must have stepped on your dick somewhere. Let's stop this discussion.

That would be great. Can you move on without being the one having the last word?

**Comment by grammoboy2** [comment]
Let's give the author of LV2 the last words. It seems to me a lot of it has been warned for in the past (most notably the mess it will create, warned by less skilled coders or even users who probably wants less confusing solutions for problems or are looking to things differently then (highly talented?) coders who come up with the most sophisticated but not the most simple solutions). 

http://drobilla.net/2019/11/11/lv2-the-good-bad-and-ugly.html
http://drobilla.net/2019/11/13/cleaning-up-the-lv2-extension-mess.html

**Comment by falkTX** [comment]
And I will also quote myself, since you seemed to ignore this part perhaps

> LV2 surely has its issues, but it is by far the best we have right now.

Those 2 links are actually very useful, thanks for bringing them to the topic.
One major thing you are not aware of probably, is that the community is taking major steps to make things better.
If you read the 1st link carefully, you will notice that it mentions the steps currently in progress to make that happen.

Also, LV2 has those issues most because of its LADSPA legacy.
Control ports, connect-port, Turtle (in case of LADSPA it is LRDF, which is pretty similar), lack of quality control and missing C++ and other language bindings.
One the non-LADSPA related issues mentioned (Library spam) already has a release in sight.

If we are going to criticize LV2, we have to note that LADSPA has pretty much all its problems without any of the solutions.


The 2nd link is Dave thinking out loud on how to do a cleanup of the existing extensions.
LADSPA does not have this problem for sure, since it has no extensions. but then... well... it has no extensions ;)

**Pull request closed without merging**
