### PR TITLE
Add /nsm/server/stop . Reasoning inside.

### PR DESCRIPTION
**Pull request by diovudau**
Add /nsm/server/stop to the client-to-server control messages. Now clients can instruct nsmD to tell themselves to stop. This enables the client behaviour to, for example, ignore local close events (like from X11) and instead ask NSM to send the proper quit signal. The result is that NSM actually awaits the client quitting and does not respond with '...died unexpectedly' anymore

### CODE REVIEW

**Comment by original-male** [comment]
Is the entire purpose of this just to get rid of the 'died unexpectedly' message? I left such a request out of the protocol because it seemed like an unnecessary complication and sudden client death needed to be handled anyway. I wouldn't want to add it unless it solved an actual problem.

**Comment by hilbrichtsoftware** [comment]
It is not only the message. It makes creating applications easier and more streamlined. 
There is only one channel to make the program quit and that is the NSM signal. 
With the server/stop message programs don't need to internally distinguish between the origin of the wish to quit, like the must do at the moment.

**Comment by original-male** [comment]
I'm still not sure I understand the problem. All a program has to do to quit NSM currently is just terminate (no need to send any message). Could you provide a specific example?

**Comment by original-male** [comment]
Perhaps I can clear one thing up: any unix program really needs to handle SIGTERM anyway. That is your single channel. With NSM, nothing changes, the program still needs to handle SIGTERM (and maybe some additional signal from your GUI toolkit, which can just invoke your sigterm handler...) You just can't get away from handling SIGTERM if you want a program that exits cleanly.

**Comment by original-male** [comment]
Also and FYI, you can have your program send itself a SIGTERM if that's more convenient than however you're having to exit with the toolkit you're using...

**Comment by hilbrichtsoftware** [comment]
I am aware that SIGTERM must be handled and that NSM sends SIGTERM as an exit signal.
On second thought: this is only about the message.

**Comment by hilbrichtsoftware** [comment]
So what is the reason against such a message and therefore a more complete API control that allows for other, yet unknown but potentially genius, usecases?

**Comment by original-male** [comment]
Well, basically just the KISS principle. Also, if this were added to the API and a client was released that depended on it, then that client would only function correctly in new versions of NSM, unless it had compatibility code for servers without that capability, in which case you gain nothing in terms of simplicity...

**Pull request closed without merging**
