### PR TITLE
Add message /nsm/gui/session/root to ask for the absolute path of the…

### PR DESCRIPTION
**Pull request by diovudau**
Here is the discussed session root patch.

### CODE REVIEW

**Comment by original-male** [comment]
This is going to sound like a really nitpicky comment, but this looks like a 6 line patch for a 1 line change. Am I missing something? Is the message path supposed to be different in the IF and ELSE blocks? The "gui_announce" and "server_annouce" messages depend on "is_reply", but it looks like the "session/root" message is common to both. I'd have to re-familiarize myself with the code to really know what the implications are of sending that message in each context. Anyway, just want to make sure I'm understanding it right.

**Comment by diovudau** [comment]
Yes, possible. It is just an oversight by me.

**Comment by original-male** [comment]
Something else occurs to me: If your GUI is starting nsmd, then you already know the session root, because it's going to either by the default, or whatever you pass to nsmd on its command line. The only time you wouldn't know is if nsmd is already running, but that situation is already one that requires some manual fiddling from the user to set environment variables etc. and requiring them to pass the session root (if not the default) to the GUI too doesn't seem outrageous. Or am I missing something about your setup?

**Comment by diovudau** [comment]
Informed-guessing the root or requiring an external source to provide it requires external knowledge or querying. Which should not be needed.

**Comment by original-male** [comment]
Serious question:  why don't you just contribute to RaySession instead, since everyone seems to agree that a copycat clones is the way to go. Can you all least just focus on the one clone? Is the desire to use GTK instead of QT, or Wayland or what?

**Comment by diovudau** [comment]
Because Session Management is a serious piece of infrastructure and should be centralised. RaySession is an incompatible re-implementation of the server. By now, from my countless messages and years of support, you should have gotten that my interest is to keep everything upstream.

**Comment by original-male** [comment]
I think the ship may have sailed already. Ubuntu Studio is recommending RaySession. People really don't care how chaotic things become, as long as they get a GTK/QT GUI. Just because you care don't mean they'll use your GUI (ask me know I know...)

**Comment by diovudau** [comment]
UbuntuStudio ships RaySession because of NTK. That is the whole and only reason. They don't want the FLTK fork.

**Comment by original-male** [comment]
And FLTK didn't want my improvements, so here we are... Probably a 2 line WAF change to build with FLTK instead of NTK anyway, but people would rather re-invent the whole thing than touch FLTK with a barge pole...

**Comment by diovudau** [comment]
You really need to get the right perspective on the whole GUI thing.  You have every right to design the official GUI as bare-bones experience that has no redundant functionality but requires an experienced user (see github-issue about tab completition from a few years ago).   But that is not all the users in existence. I teach classes every day using NSM and the real word experience from actual user testing, feedback and review is that a base level of convenience (for the cost of redundancy) is indeed needed.

My planned GUI is foremost for this special case, my classes. But it may be useful for other people.

Don't think that this is designed to take away your fame, reputation or negate your good work on the NSM implementation and ruleset.  

There is no one-size fits.

**Comment by original-male** [comment]
Fame? All I've gotten from sharing this project is grief and harassment and now immitation. I should have kept it to myself.

**Comment by falkTX** [comment]
I spoke with @ErikMeyer about this, they were hoping to leverage some pre-existing packages from KXStudio for UbuntuStudio.
It worked for Carla and I think a few other packages, but yeah, for NON stuff NTK is really a problem.

UbuntuStudio folks are packagers, not developers.
They did not want to maintain a custom NON version just to get NSM to work.

And by the way, the issue of SM came because of LADISH.
LADISH has not seen any updates in a very long time, plus its GUI has dependencies which are not even available in Debian/Ubuntu anymore. So basically LADISH is on the way to being removed from Debian, and thus Ubuntu and its variants.
The UbuntuStudio team started a search for a replacement SM.
We (in #lad) tried to push for the original NSM as much as we could, but Debian (and Ubuntu) packaging standards are pretty strict.
RaySession was considered after evaluating other options. This one actually builds, installs and works. It is somewhat sad that it is being pushed as the go-to SM for Ubuntu folks, but all other options were simply not there in a way that they could get to work.

Now, @diovudau is carefully trying to do things in a way that still gets us back to NSM with nsmd being the go-to implementation. It seems his efforts are not being appreciated at all by you @original-male :(
He was the one keeping the NSM related wiki updated, always pushing for it as the best SM in public channels, and even making his own new tools he made specially for use in NSM.

You are destroying your own little community, please reconsider your actions and what you say a bit more carefully.
Thank you

**Comment by diovudau** [comment]
Well, how goes the saying..  imitation is the sincerest form of flattery :)

**Comment by original-male** [comment]
@diovudau It isn't so much about being bare bones as it is putting the functionality in the right place. But yes, for me NSM does 120% of what I need and it works 100% of the time, so changing anything seems an awful lot pointless churn to me. But anyway, as I've said elsewhere, to do the launcher/tab-completion doesn't require any change to NSM. This can be a client or separate program that anyone can write, in any TK they please, that can work with any of the (are we at a dozen yet?) implementations of the NSM GUI, no need for pointless duplication!... What community is there if people don't want to discuss how thing can be improved, but instead prefer to just start implementing without a second thought? I put a huge amount of thought and planning into NSM before releasing it, so that I wouldn't waste anyone else's time. I only wish that others would show the same consideration and think before acting.

**Comment by diovudau** [comment]
Then let us stay realistic and technical.
Headcount: Your GUI obviously, RaySession (which is technically not an NSM GUI because it is a protocol-reimplementation) and that is it. There are no other GUIs. I have a prototype that has no public release because I am actually discussing things beforehand.

**Comment by falkTX** [comment]
The lack of communication from some might be because they do not want to deal with you, due to previous bad history from how others were handled.

As @diovudau says, right now it is only nsmd with NTK UI and RaySession, nothing else.
You are quite upset about what 1 single person did.
Let's be reasonable, what one person does is not a collective action or symbol of an entire group.
I am yet to add RaySession to the KXStudio repositories, for example, as I did not want to spread its usage too much until it was clear how we should proceed with SM as a community.


Don't take me wrong please...
NSM is great, and it is really awesome that works for you.

We want to make it work for us too, and have been reporting and discussing a few things on how to make it so.
Right now, for me personally, the lack of discoverability of available NSM applications is a blocker.

I have no experience at all with FLTK as UI,
Most people/developers also don't use FLTK, so contributing to the UI means learning a new toolkit, which they might feel discouraged to learn.
That makes it a high-level barrier of entry.


Maybe I am wrong, but having a single nsmd and different NSM UIs / control-panels would be a good thing, right?

**Comment by original-male** [comment]
@diovudau But you're discussing it from the position of somehow who has already decided not to contribute to improving this project. I still don't have the faintest idea what your GUI will do that the stock GUI doesn't, other than certainly be written in another toolkit. IMHO, the work that should have been undertaken prior to writing your prototype (and I should think you've already done it but not shared the result) is the formal documentation of the NSM GUI protocol, so that we can somehow agree to version and lock it down to prevent future breakage, and that you have something to work from when implementing your implementation of one end of that protocol, and that the next guy who wants to do it can avoid duplicating at least that effort. This is especially important if you are planning something (as you appear to be) that doesn't have feature parity with the stock GUI, since you might need many more of these extensions to make it work, and it's far more efficient to determine the minimum set when you have at least a complete set, rather than one request at a time.

**Comment by original-male** [comment]
@falkTX A good thing? I don't know. I mean, we're used to there being a kThis and a gThis. That would be a different matter, because those would presumably have feature parity with the stock GUI and their only purpose would be to use a different TK. I think even that is stupid, personally, but you may have noticed by now that I have very strong views on what is an isn't appropriate use of developer time.

I don't have any hard feelings myself. But yes, everyone is going to get pissy when they come to me with a feature request that I deem scope creep or duplication of effort. Unfortunately, it's always going to be that way. Nobody likes Linus either, but he's doing an important job. IMHO, none of this software would have anything good about it if I were to allow everyone's whims to turn it into another bloated everything-and-the-kitchen-sink mess. Getting away from that was the whole freaking point of spending decades of my life building this.

**Comment by diovudau** [comment]
My decision to already start is based on previous discussions and readings. You think that a separate launcher is the way to go. But that has to be added to the session as well (btw. pcmanfm works for this, eventhough overkill), so there is at least one program you need to type in. That is too much. Not for your users, but for mine.

Same with filemanager functionality. You don't want deletion, symlink resolving and archiving (properly labeled to make the functionality clear), but these are reasonable features to have. 

These are two confliction standpoints, I do not anticipate you changing the GUI to support them but I need this features, by design, because I know my users. 

The most sensible course of action is to NOT enhance the protocol with many more features. The current pull request is already an exception. My design will be to use extra clients, like jack patch, for everything else. 100% compatibility in both directions is the goal. Everything in these sessions will work with nsm, and everything will work with mine.

**Comment by falkTX** [comment]
Linus had to step down for some time and take counseling as he finally heard his community complaints about his behavior.
Long gone are his personal attacks and pissy-fight rants, his attitude changed for the better.

Having the "old" Linus as an example of behaviour is not exactly a great thing you know...

**Comment by grammoboy2** [comment]
> My decision to already start is based on previous discussions and 
> readings. You think that a separate launcher is the way to go. But 
> that has to be added to the session as well (btw. pcmanfm works for 
> this, eventhough overkill), so there is at least one program you need 
> to type in. That is too much. Not for your users, but for mine.
>
Are you sure about this? I did some work with kids and was amazed how 
easy 5 year old kids without programming experience could copy stuff 
from a example youtube video to do some simple Scratch programming. A 
short simple youtube tutorial video could help here probably.

Also it might be possible to make a template for students with jackpatch 
and a separate launcher already there.

> Same with filemanager functionality. You don't want deletion, symlink 
> resolving and archiving (properly labeled to make the functionality 
> clear), but these are reasonable features to have.
>
Afaik some sort of deletion might be possible with NSM in the future. I 
wonder whether students needs symlink resolving and archiving when 
typing in a application is already a bridge too far. I don't mean this 
cynical or so, I'm taking your examples seriously.

**Comment by original-male** [comment]
@falkTX That's a very shallow view of the psychology involved. People get upset and resentful when you tell them "no", or "not good enough", no matter how you do it. They show their resentment in various ways, injurious to Linus, and transmits that aggression to the next person in line. Linus changing his behavior (probably also injurious to him), does nothing to address the root problem... Unless he stops telling people "no" and "do better", but that would obviously harm the project. And as long as we're comparing: Linus merges all kinds of stuff that I wouldn't ;-)

**Comment by original-male** [comment]
@diovudau I never said I was against those archiving features. Again, I care more about *where* the functionality goes than that it exists at all. Like I said in another discussion, it would probably best to have a message sent to the clients to bundle their own projects, because, for one thing, not everybody is going to use symlinks (they'll have external file references buried in their private project files).

Maybe I haven't done a good enough job of communicating it, but the situation is less one of my rejecting things outright, and more one of my rejecting an incomplete, draft version of the idea.

For example with the launcher. I never said it *has* to be a client added to the session. That's just a draft idea, and as you point out yourself, it has problems. There are other ways to do it and maintain the important aspect that it is a separate program. For example, NSM GUI could have a config file that has LauncherProgram=foo line in it and then clicking "add" just starts that program (with the appropriate NSM_URL env value just as would be passed to a client in the session.

You all give up to easily.

**Comment by original-male** [comment]
Re @grammoyboys2's comment. Yes, he has convinced me to add session removal. I think that really should be the extent of file management-type features though. The world already has enough file managers.

**Comment by original-male** [comment]
Does anyone know who the author of RaySession is anyway? I can't find a name or email address. I'd like to send him a brief message informing him what piece of shit he is.

**Comment by falkTX** [comment]
@original-male your attitude is abhorrent, I want nothing to do with you.

You actively hurt the NSM project.
Just FYI, there are quite a few devs (note, plural) that voiced the opinion of not liking NSM specifically because of you, and I am not talking about myself here.

**Pull request merged**
